spring:
    flyway:
        locations: classpath:/test/db/migration
    application:
        name: register
    datasource:
        driver-class-name: ${TEST_DB_DRIVER:org.h2.Driver}
        url: ${TEST_DB_URL:jdbc:h2:mem:register}
        username: ${TEST_DB_USERNAME:sa}
        password: ${TEST_DB_PASSWORD:sa}
    jpa:
        hibernate.ddl-auto: none
    jackson:
        mapper:
            ACCEPT_CASE_INSENSITIVE_ENUMS: true
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: true
            FAIL_ON_MISSING_CREATOR_PROPERTIES: true

api:
    security:
        token:
            secret: ${JWT_SECRET:test}