server:
    port: ${SERVER_PORT:9000}
spring:
    application:
        name: register
    datasource:
        driver-class-name: ${DB_DRIVER}
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate.ddl-auto: create-drop
    jackson:
        mapper:
            ACCEPT_CASE_INSENSITIVE_ENUMS: true
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: true
            FAIL_ON_MISSING_CREATOR_PROPERTIES: true

api:
    security:
        token:
            secret: ${JWT_SECRET}