server:
    port: ${SERVER_PORT:8080}
spring:
    application:
        name: register
    datasource:
        driver-class-name: ${DBASE_DRIVER}
        url: ${DBASE_URL}
        username: ${DBASE_USERNAME}
        password: ${DBASE_PASSWORD}
    jpa:
        hibernate.ddl-auto: none
    jackson:
        mapper:
            ACCEPT_CASE_INSENSITIVE_ENUMS: true
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: true
            FAIL_ON_MISSING_CREATOR_PROPERTIES: true

api:
    security:
        token:
            secret: ${JWT_SECRET}